[package]
name = "lemma-db-sqlite"
edition.workspace = true
version.workspace = true

[dependencies]
lemma-core.workspace = true
lemma-session.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
uuid = { workspace = true, features = ["serde"] }

[lints]
workspace = true
