[package]
version.workspace = true
edition.workspace = true
name = "lemma-db-pgsql"

[dependencies]
chrono.workspace = true
lemma-core.workspace = true
lemma-provider.workspace = true
lemma-session.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
uuid.workspace = true

[lints]
workspace = true
