[package]
version.workspace = true
edition.workspace = true
name = "lemma-auth"

[dependencies]
argon2.workspace = true
chrono.workspace = true
hex.workspace = true
jsonwebtoken.workspace = true
rand.workspace = true
serde.workspace = true
sha2.workspace = true
uuid.workspace = true

[lints]
workspace = true
