[package]
version.workspace = true
edition.workspace = true
name = "lemma-server"

[dependencies]
axum.workspace = true
connectrpc.workspace = true
dotenvy.workspace = true
lemma-adapter.workspace = true
lemma-agent-rpc.workspace = true
lemma-auth-rpc.workspace = true
lemma-conversation-rpc.workspace = true
lemma-db-pgsql.workspace = true
lemma-db-sqlite.workspace = true
lemma-provider-rpc.workspace = true
lemma-session.workspace = true
rust-embed.workspace = true
sqlx.workspace = true
tokio.workspace = true
tower-http.workspace = true
uuid.workspace = true

[lints]
workspace = true
